### ISSUE TITLE
Build error - namespace name 'UI' does not exist in the namespace Microsoft.AspNetCore.Identity

### ISSUE THREAD

**Issue by sharuman** [RijadGerguri/HotelManagement#1]
After running `PM> add-migration xxx` command I got 9 error messages:
 
project/HotelManagement/HotelManagement/Areas/Identity/IdentityHostingStartup.cs(5,37,5,39): error CS0234: The type or namespace name 'UI' does not exist in the namespace 'Microsoft.AspNetCore.Identity' (are you missing an assembly reference?)
project/HotelManagement/HotelManagement/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs(9,37,9,39): error CS0234: The type or namespace name 'UI' does not exist in the namespace 'Microsoft.AspNetCore.Identity' (are you missing an assembly reference?)
project/HotelManagement/HotelManagement/Areas/Identity/Pages/Account/Login.cshtml.cs(10,37,10,39): error CS0234: The type or namespace name 'UI' does not exist in the namespace 'Microsoft.AspNetCore.Identity' (are you missing an assembly reference?)
project/HotelManagement/HotelManagement/Areas/Identity/Pages/Account/Register.cshtml.cs(11,37,11,39): error CS0234: The type or namespace name 'UI' does not exist in the namespace 'Microsoft.AspNetCore.Identity' (are you missing an assembly reference?)
project/HotelManagement/HotelManagement/Areas/Identity/Pages/Account/Register.cshtml.cs(25,26,25,38): error CS0246: The type or namespace name 'IEmailSender' could not be found(are you missing a using directive or an assembly reference?)
project/HotelManagement/HotelManagement/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs(20,26,20,38): error CS0246: The type or namespace name 'IEmailSender' could not be found(are you missing a using directive or an assembly reference?)
project/HotelManagement/HotelManagement/Areas/Identity/Pages/Account/Register.cshtml.cs(33,13,33,25): error CS0246: The type or namespace name 'IEmailSender' could not be found(are you missing a using directive or an assembly reference?)
project/HotelManagement/HotelManagement/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs(22,75,22,87): error CS0246: The type or namespace name 'IEmailSender' could not be found(are you missing a using directive or an assembly reference?)"

List of installed packages including [Microsoft.AspNetCore.Identity.UI](https://www.nuget.org/packages/Microsoft.AspNetCore.Identity.UI):
![Screenshot 2020-12-24 at 20 58 24](https://user-images.githubusercontent.com/7173038/103104965-e933f800-462a-11eb-8495-a45e9759ce62.png)

**Comment by RijadGerguri** [comment]
Double click in 'HotelManagement' and replace everything with below text:
![image](https://user-images.githubusercontent.com/35470305/103106034-7595e900-4632-11eb-9d05-19a1447d836e.png)

`<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UserSecretsId>ed0618f1-6c07-424f-956d-f909a348df80</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.1.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.4" />
  </ItemGroup>

</Project>`

**Comment by sharuman** [comment]
@RijadGerguri I reverted @nferati changes on my local machine and it still fails to build with 5.x packages.
Since this project was created using 3.x packages, perhaps, we should start from scratch with the latest packages (5.x) and see?

**Comment by RijadGerguri** [comment]
You can try again now @sharuman. I just migrated the project to .net 5.0 and everything should work fine.

**Comment by sharuman** [comment]
Is it running correctly on your machine? I saw your changes (#32c6595274e7b2945926aeb37f22c06673f35cca) and they are not fixing the missing/wrong references to `Microsoft.AspNetCore.Identity.UI.xyz` and the build is still failing.

**Comment by sharuman** [comment]
For some unknown reason I was getting an incompatibility issue when trying to update (3,x -> 5.x)`Microsoft.EntityFrameworkCore.Design` package. Reinstalling Visual Studio (for Mac) to fixed it.

The fix pushed in (32c6595274e7b2945926aeb37f22c06673f35cca) will be futile if your project's Target Framework is not pointing to .NET Core 5.x.

In Visual Studio go to `Project -> <Project name> Options -> Build -> General`:
<img width="896" alt="Screenshot 2020-12-26 at 15 13 44" src="https://user-images.githubusercontent.com/7173038/103153146-a55a0380-478e-11eb-965a-b23b42a89d13.png">
